# Generated by Django 3.0.5 on 2021-05-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fake',
            new_name='Book',
        ),
    ]
